language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t anshup7/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true anshup7/docker-react npm run test -- --coverage

after_success:
  - docker build -t anshup7/multi-client ./client
  - docker build -t anshup7/multi-nginx ./nginx
  - docker build -t anshup7/multi-server ./server
  - docker build -t anshup7/multi-worker ./worker

# Login to Docker hub
echo "$PASSWORD" | docker login -u "$USER_NAME" --password-stdin
#Push the images to docker hub
- docker push anshup7/multi-client
- docker push anshup7/multi-nginx
- docker push anshup7/multi-server
- docker push anshup7/multi-worker

# deploy:
#   provider: elasticbeanstalk
#   region: us-west-2
#   app: "docker-react"
#   env: "DockerReact-env"
#   bucket_name: "elasticbeanstalk-us-west-2-959466835251"
#   bucket_path: "docker-react"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: "$AWS_SECRET_KEY"