language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t anshup7/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true anshup7/react-test npm run test -- --coverage

after_success:
  - docker build -t anshup7/multi-client ./client
  - docker build -t anshup7/multi-nginx ./nginx
  - docker build -t anshup7/multi-server ./server
  - docker build -t anshup7/multi-worker ./worker

  # Login to Docker hub
  - echo "$PASSWORD" | docker login -u "$USER_NAME" --password-stdin
  #Push the images to docker hub
  - docker push anshup7/multi-client
  - docker push anshup7/multi-nginx
  - docker push anshup7/multi-server
  - docker push anshup7/multi-worker
